"""add hotel_code in hotel model

Revision ID: 6f4ec33a2d9b
Revises: 29337cc0c0ca
Create Date: 2026-09-08 12:35:19.979705

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f4ec33a2d9b'
down_revision = '29337cc0c0ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hotels', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hotel_code', sa.String(length=20), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hotels', schema=None) as batch_op:
        batch_op.drop_column('hotel_code')

    # ### end Alembic commands ###
