"""Added staff field in hotel model

Revision ID: 88d939ca6772
Revises: ce3722117917
Create Date: 2026-09-08 15:23:59.515083

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88d939ca6772'
down_revision = 'ce3722117917'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hotels', schema=None) as batch_op:
        batch_op.add_column(sa.Column('staff_key', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hotels', schema=None) as batch_op:
        batch_op.drop_column('staff_key')

    # ### end Alembic commands ###
