"""changed user,hotel model

Revision ID: 921f864693f3
Revises: 6f4ec33a2d9b
Create Date: 2026-09-08 13:21:12.282431

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '921f864693f3'
down_revision = '6f4ec33a2d9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hotels', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['hotel_code'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hotel_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'hotels', ['hotel_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('hotel_id')

    with op.batch_alter_table('hotels', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
