"""removed price_per_night from RoomType and added in Room

Revision ID: ce3722117917
Revises: 921f864693f3
Create Date: 2026-09-08 14:52:34.036651

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ce3722117917'
down_revision = '921f864693f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('room_types', schema=None) as batch_op:
        batch_op.drop_column('price_per_night')

    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price_per_night', sa.Numeric(precision=10, scale=2), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.drop_column('price_per_night')

    with op.batch_alter_table('room_types', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price_per_night', mysql.DECIMAL(precision=10, scale=2), nullable=False))

    # ### end Alembic commands ###
